### ISSUE TITLE
Android: საჭიროა მონაცემების წამოღება სერვერიდან

### ISSUE THREAD

**Issue by developer--** [developer--/GraphiteFinder#6]
საჭიროა ნამუშევრის შესახებ ინფორამციის წამოღება სერვერიდან GraphitItemModel კლასისთვის. ლისტვიუზე განსათავსებლად

**Comment by developer--** [comment]
ველოდები jsons

**Comment by lashatsatsashvili** [comment]
dawerilimaq mara serveris problema configis

**Comment by developer--** [comment]
done
